cache:
  directories:
  - .autoconf
  - $HOME/.m2
jobs:
  include:
    - language: java
      stage: JEOrg Spring Master 5 Full (Codacy/Coveralls/Codecov reports - Limited Logs)
      jdk:
        - openjdk11
      cache:
        directories:
        - .autoconf
        - $HOME/.m2
      install:
        - mvn dependency:resolve | egrep "Building|Tests|SpringBoot|jesperancinha"
      script:
        - mvn clean install coveralls:report -Dconsolerizer.show=false -DrepoToken=${COVERALLS_TOKEN} | egrep "Building|Tests|SpringBoot|jesperancinha"
        - bash <(curl -s https://codecov.io/bash)
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java Kotlin $(find **/jacoco*.xml -printf '-r %p ')
